server:
  port: 8008

spring:
  application:
    name: service-statistics
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.132.130:3306/guli
    username: root
    password: luoqi@123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.132.130:8848
#  redis:
#    host: 101.132.132.130
#    port: 8081
#    database: 1
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
#    password: qwe@179
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
