server:
  port: 8222

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      server-addr: 101.132.132.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-cms
        uri: lb://service-cms
        predicates:
        - Path=/educms/**
      - id: service-edu
        uri: lb://service-edu
        predicates:
        - Path=/eduservice/**
      - id: service-vod
        uri: lb://service-vod
        predicates:
        - Path=/eduvod/**
      - id: service-oss
        uri: lb://service-oss
        predicates:
        - Path=/eduoss/**
      - id: service-ucenter
        uri: lb://service-ucenter
        predicates:
        - Path=/educenter/**
      - id: service-msm
        uri: lb://service-msm
        predicates:
        - Path=/edumsm/**
      - id: service-order
        uri: lb://service-order
        predicates:
        - Path=/eduorder/**
      - id: service-statistics
        uri: lb://service-statistics
        predicates:
        - Path=/edustatistics/**
