server:
  port: 8004
spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.132.130:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: luoqi@123
  #返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      server-addr: 101.132.132.130:8848
  redis:
    host: 101.132.132.130
    port: 8081
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: qwe@179
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml